[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NETLIFY = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 5173
